// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: todo.proto
// Protobuf C++ Version: 6.31.1

#include "todo.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace ToDoService {
namespace v1 {
template <typename>
PROTOBUF_CONSTEXPR UpdateItemRes::UpdateItemRes(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(UpdateItemRes_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct UpdateItemResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateItemResDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateItemResDefaultTypeInternal() {}
  union {
    UpdateItemRes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateItemResDefaultTypeInternal _UpdateItemRes_default_instance_;

inline constexpr ToDo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        description_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        status_{static_cast< ::ToDoService::v1::Status >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR ToDo::ToDo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ToDo_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ToDoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ToDoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ToDoDefaultTypeInternal() {}
  union {
    ToDo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ToDoDefaultTypeInternal _ToDo_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR StreamUpdateChangeReq::StreamUpdateChangeReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(StreamUpdateChangeReq_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct StreamUpdateChangeReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StreamUpdateChangeReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StreamUpdateChangeReqDefaultTypeInternal() {}
  union {
    StreamUpdateChangeReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StreamUpdateChangeReqDefaultTypeInternal _StreamUpdateChangeReq_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR GetListReq::GetListReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(GetListReq_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct GetListReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetListReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetListReqDefaultTypeInternal() {}
  union {
    GetListReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetListReqDefaultTypeInternal _GetListReq_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR AddItemRes::AddItemRes(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(AddItemRes_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct AddItemResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AddItemResDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AddItemResDefaultTypeInternal() {}
  union {
    AddItemRes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AddItemResDefaultTypeInternal _AddItemRes_default_instance_;

inline constexpr AddItemReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        description_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR AddItemReq::AddItemReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(AddItemReq_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AddItemReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AddItemReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AddItemReqDefaultTypeInternal() {}
  union {
    AddItemReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AddItemReqDefaultTypeInternal _AddItemReq_default_instance_;

inline constexpr UpdateItemReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        todo_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR UpdateItemReq::UpdateItemReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(UpdateItemReq_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UpdateItemReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateItemReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateItemReqDefaultTypeInternal() {}
  union {
    UpdateItemReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateItemReqDefaultTypeInternal _UpdateItemReq_default_instance_;

inline constexpr StreamUpdateChangeRes::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        todo_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR StreamUpdateChangeRes::StreamUpdateChangeRes(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(StreamUpdateChangeRes_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct StreamUpdateChangeResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StreamUpdateChangeResDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StreamUpdateChangeResDefaultTypeInternal() {}
  union {
    StreamUpdateChangeRes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StreamUpdateChangeResDefaultTypeInternal _StreamUpdateChangeRes_default_instance_;

inline constexpr GetListRes::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : todo_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetListRes::GetListRes(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(GetListRes_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetListResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetListResDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetListResDefaultTypeInternal() {}
  union {
    GetListRes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetListResDefaultTypeInternal _GetListRes_default_instance_;
}  // namespace v1
}  // namespace ToDoService
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_todo_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_todo_2eproto = nullptr;
const ::uint32_t
    TableStruct_todo_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::ToDoService::v1::ToDo, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::ToDoService::v1::ToDo, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::ToDoService::v1::ToDo, _impl_.description_),
        PROTOBUF_FIELD_OFFSET(::ToDoService::v1::ToDo, _impl_.status_),
        0,
        1,
        2,
        0x000, // bitmap
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::ToDoService::v1::GetListRes, _impl_.todo_),
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::ToDoService::v1::AddItemReq, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::ToDoService::v1::AddItemReq, _impl_.description_),
        0,
        0x000, // bitmap
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::ToDoService::v1::UpdateItemReq, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::ToDoService::v1::UpdateItemReq, _impl_.todo_),
        0,
        0x000, // bitmap
        0x000, // bitmap
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::ToDoService::v1::StreamUpdateChangeRes, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::ToDoService::v1::StreamUpdateChangeRes, _impl_.todo_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::ToDoService::v1::ToDo)},
        {9, sizeof(::ToDoService::v1::GetListReq)},
        {10, sizeof(::ToDoService::v1::GetListRes)},
        {12, sizeof(::ToDoService::v1::AddItemReq)},
        {17, sizeof(::ToDoService::v1::AddItemRes)},
        {18, sizeof(::ToDoService::v1::UpdateItemReq)},
        {23, sizeof(::ToDoService::v1::UpdateItemRes)},
        {24, sizeof(::ToDoService::v1::StreamUpdateChangeReq)},
        {25, sizeof(::ToDoService::v1::StreamUpdateChangeRes)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::ToDoService::v1::_ToDo_default_instance_._instance,
    &::ToDoService::v1::_GetListReq_default_instance_._instance,
    &::ToDoService::v1::_GetListRes_default_instance_._instance,
    &::ToDoService::v1::_AddItemReq_default_instance_._instance,
    &::ToDoService::v1::_AddItemRes_default_instance_._instance,
    &::ToDoService::v1::_UpdateItemReq_default_instance_._instance,
    &::ToDoService::v1::_UpdateItemRes_default_instance_._instance,
    &::ToDoService::v1::_StreamUpdateChangeReq_default_instance_._instance,
    &::ToDoService::v1::_StreamUpdateChangeRes_default_instance_._instance,
};
const char descriptor_table_protodef_todo_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\ntodo.proto\022\016ToDoService.v1\"O\n\004ToDo\022\n\n\002"
    "id\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022&\n\006status\030"
    "\003 \001(\0162\026.ToDoService.v1.Status\"\014\n\nGetList"
    "Req\"0\n\nGetListRes\022\"\n\004ToDo\030\001 \003(\0132\024.ToDoSe"
    "rvice.v1.ToDo\"!\n\nAddItemReq\022\023\n\013descripti"
    "on\030\002 \001(\t\"\014\n\nAddItemRes\"3\n\rUpdateItemReq\022"
    "\"\n\004todo\030\001 \001(\0132\024.ToDoService.v1.ToDo\"\017\n\rU"
    "pdateItemRes\"\027\n\025StreamUpdateChangeReq\";\n"
    "\025StreamUpdateChangeRes\022\"\n\004todo\030\001 \001(\0132\024.T"
    "oDoService.v1.ToDo*$\n\006Status\022\013\n\007PENDING\020"
    "\000\022\r\n\tCOMPLETED\020\0012\305\002\n\013ToDoService\022A\n\007GetL"
    "ist\022\032.ToDoService.v1.GetListReq\032\032.ToDoSe"
    "rvice.v1.GetListRes\022A\n\007AddItem\022\032.ToDoSer"
    "vice.v1.AddItemReq\032\032.ToDoService.v1.AddI"
    "temRes\022J\n\nUpdateItem\022\035.ToDoService.v1.Up"
    "dateItemReq\032\035.ToDoService.v1.UpdateItemR"
    "es\022d\n\022StreamUpdateChange\022%.ToDoService.v"
    "1.StreamUpdateChangeReq\032%.ToDoService.v1"
    ".StreamUpdateChangeRes0\001b\006proto3"
};
static ::absl::once_flag descriptor_table_todo_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_todo_2eproto = {
    false,
    false,
    752,
    descriptor_table_protodef_todo_2eproto,
    "todo.proto",
    &descriptor_table_todo_2eproto_once,
    nullptr,
    0,
    9,
    schemas,
    file_default_instances,
    TableStruct_todo_2eproto::offsets,
    file_level_enum_descriptors_todo_2eproto,
    file_level_service_descriptors_todo_2eproto,
};
namespace ToDoService {
namespace v1 {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Status_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_todo_2eproto);
  return file_level_enum_descriptors_todo_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Status_internal_data_[] = {
    131072u, 0u, };
// ===================================================================

class ToDo::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ToDo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ToDo, _impl_._has_bits_);
};

ToDo::ToDo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ToDo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ToDoService.v1.ToDo)
}
PROTOBUF_NDEBUG_INLINE ToDo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::ToDoService::v1::ToDo& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        id_(arena, from.id_),
        description_(arena, from.description_) {}

ToDo::ToDo(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ToDo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ToDo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ToDo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.status_ = from._impl_.status_;

  // @@protoc_insertion_point(copy_constructor:ToDoService.v1.ToDo)
}
PROTOBUF_NDEBUG_INLINE ToDo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        id_(arena),
        description_(arena) {}

inline void ToDo::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.status_ = {};
}
ToDo::~ToDo() {
  // @@protoc_insertion_point(destructor:ToDoService.v1.ToDo)
  SharedDtor(*this);
}
inline void ToDo::SharedDtor(MessageLite& self) {
  ToDo& this_ = static_cast<ToDo&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.id_.Destroy();
  this_._impl_.description_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ToDo::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ToDo(arena);
}
constexpr auto ToDo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ToDo),
                                            alignof(ToDo));
}
constexpr auto ToDo::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ToDo_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ToDo::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ToDo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ToDo::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ToDo>(), &ToDo::ByteSizeLong,
              &ToDo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ToDo, _impl_._cached_size_),
          false,
      },
      &ToDo::kDescriptorMethods,
      &descriptor_table_todo_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ToDo_class_data_ =
        ToDo::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ToDo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ToDo_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ToDo_class_data_.tc_table);
  return ToDo_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 41, 2>
ToDo::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ToDo, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ToDo_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ToDoService::v1::ToDo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ToDo, _impl_.id_)}},
    // string description = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(ToDo, _impl_.description_)}},
    // .ToDoService.v1.Status status = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ToDo, _impl_.status_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(ToDo, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string id = 1;
    {PROTOBUF_FIELD_OFFSET(ToDo, _impl_.id_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string description = 2;
    {PROTOBUF_FIELD_OFFSET(ToDo, _impl_.description_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .ToDoService.v1.Status status = 3;
    {PROTOBUF_FIELD_OFFSET(ToDo, _impl_.status_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
    "\23\2\13\0\0\0\0\0"
    "ToDoService.v1.ToDo"
    "id"
    "description"
  }},
};
PROTOBUF_NOINLINE void ToDo::Clear() {
// @@protoc_insertion_point(message_clear_start:ToDoService.v1.ToDo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.id_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.description_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.status_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ToDo::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ToDo& this_ = static_cast<const ToDo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ToDo::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ToDo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:ToDoService.v1.ToDo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string id = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_id().empty()) {
      const ::std::string& _s = this_._internal_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ToDoService.v1.ToDo.id");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string description = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (!this_._internal_description().empty()) {
      const ::std::string& _s = this_._internal_description();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ToDoService.v1.ToDo.description");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // .ToDoService.v1.Status status = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (this_._internal_status() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          3, this_._internal_status(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ToDoService.v1.ToDo)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ToDo::ByteSizeLong(const MessageLite& base) {
  const ToDo& this_ = static_cast<const ToDo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ToDo::ByteSizeLong() const {
  const ToDo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:ToDoService.v1.ToDo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // string id = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_id());
      }
    }
    // string description = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!this_._internal_description().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_description());
      }
    }
    // .ToDoService.v1.Status status = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (this_._internal_status() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ToDo::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ToDo*>(&to_msg);
  auto& from = static_cast<const ToDo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ToDoService.v1.ToDo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_id().empty()) {
        _this->_internal_set_id(from._internal_id());
      } else {
        if (_this->_impl_.id_.IsDefault()) {
          _this->_internal_set_id("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!from._internal_description().empty()) {
        _this->_internal_set_description(from._internal_description());
      } else {
        if (_this->_impl_.description_.IsDefault()) {
          _this->_internal_set_description("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (from._internal_status() != 0) {
        _this->_impl_.status_ = from._impl_.status_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ToDo::CopyFrom(const ToDo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ToDoService.v1.ToDo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ToDo::InternalSwap(ToDo* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.description_, &other->_impl_.description_, arena);
  swap(_impl_.status_, other->_impl_.status_);
}

::google::protobuf::Metadata ToDo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetListReq::_Internal {
 public:
};

GetListReq::GetListReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, GetListReq_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:ToDoService.v1.GetListReq)
}
GetListReq::GetListReq(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const GetListReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, GetListReq_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetListReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:ToDoService.v1.GetListReq)
}

inline void* PROTOBUF_NONNULL GetListReq::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GetListReq(arena);
}
constexpr auto GetListReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(GetListReq),
                                            alignof(GetListReq));
}
constexpr auto GetListReq::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_GetListReq_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &GetListReq::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<GetListReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GetListReq::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<GetListReq>(), &GetListReq::ByteSizeLong,
              &GetListReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GetListReq, _impl_._cached_size_),
          false,
      },
      &GetListReq::kDescriptorMethods,
      &descriptor_table_todo_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull GetListReq_class_data_ =
        GetListReq::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GetListReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&GetListReq_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(GetListReq_class_data_.tc_table);
  return GetListReq_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
GetListReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    GetListReq_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ToDoService::v1::GetListReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata GetListReq::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetListRes::_Internal {
 public:
};

GetListRes::GetListRes(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GetListRes_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ToDoService.v1.GetListRes)
}
PROTOBUF_NDEBUG_INLINE GetListRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::ToDoService::v1::GetListRes& from_msg)
      : todo_{visibility, arena, from.todo_},
        _cached_size_{0} {}

GetListRes::GetListRes(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const GetListRes& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GetListRes_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetListRes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:ToDoService.v1.GetListRes)
}
PROTOBUF_NDEBUG_INLINE GetListRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : todo_{visibility, arena},
        _cached_size_{0} {}

inline void GetListRes::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetListRes::~GetListRes() {
  // @@protoc_insertion_point(destructor:ToDoService.v1.GetListRes)
  SharedDtor(*this);
}
inline void GetListRes::SharedDtor(MessageLite& self) {
  GetListRes& this_ = static_cast<GetListRes&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL GetListRes::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GetListRes(arena);
}
constexpr auto GetListRes::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(GetListRes, _impl_.todo_) +
          decltype(GetListRes::_impl_.todo_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(GetListRes), alignof(GetListRes), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&GetListRes::PlacementNew_,
                                 sizeof(GetListRes),
                                 alignof(GetListRes));
  }
}
constexpr auto GetListRes::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_GetListRes_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &GetListRes::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<GetListRes>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GetListRes::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<GetListRes>(), &GetListRes::ByteSizeLong,
              &GetListRes::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GetListRes, _impl_._cached_size_),
          false,
      },
      &GetListRes::kDescriptorMethods,
      &descriptor_table_todo_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull GetListRes_class_data_ =
        GetListRes::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GetListRes::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&GetListRes_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(GetListRes_class_data_.tc_table);
  return GetListRes_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
GetListRes::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    GetListRes_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ToDoService::v1::GetListRes>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .ToDoService.v1.ToDo ToDo = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetListRes, _impl_.todo_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .ToDoService.v1.ToDo ToDo = 1;
    {PROTOBUF_FIELD_OFFSET(GetListRes, _impl_.todo_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::ToDoService::v1::ToDo>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void GetListRes::Clear() {
// @@protoc_insertion_point(message_clear_start:ToDoService.v1.GetListRes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.todo_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL GetListRes::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const GetListRes& this_ = static_cast<const GetListRes&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL GetListRes::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const GetListRes& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:ToDoService.v1.GetListRes)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .ToDoService.v1.ToDo ToDo = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_todo_size());
       i < n; i++) {
    const auto& repfield = this_._internal_todo().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ToDoService.v1.GetListRes)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t GetListRes::ByteSizeLong(const MessageLite& base) {
  const GetListRes& this_ = static_cast<const GetListRes&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t GetListRes::ByteSizeLong() const {
  const GetListRes& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:ToDoService.v1.GetListRes)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .ToDoService.v1.ToDo ToDo = 1;
    {
      total_size += 1UL * this_._internal_todo_size();
      for (const auto& msg : this_._internal_todo()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void GetListRes::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetListRes*>(&to_msg);
  auto& from = static_cast<const GetListRes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ToDoService.v1.GetListRes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_todo()->MergeFrom(
      from._internal_todo());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetListRes::CopyFrom(const GetListRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ToDoService.v1.GetListRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetListRes::InternalSwap(GetListRes* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.todo_.InternalSwap(&other->_impl_.todo_);
}

::google::protobuf::Metadata GetListRes::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AddItemReq::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<AddItemReq>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AddItemReq, _impl_._has_bits_);
};

AddItemReq::AddItemReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AddItemReq_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ToDoService.v1.AddItemReq)
}
PROTOBUF_NDEBUG_INLINE AddItemReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::ToDoService::v1::AddItemReq& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        description_(arena, from.description_) {}

AddItemReq::AddItemReq(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const AddItemReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AddItemReq_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AddItemReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:ToDoService.v1.AddItemReq)
}
PROTOBUF_NDEBUG_INLINE AddItemReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        description_(arena) {}

inline void AddItemReq::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
AddItemReq::~AddItemReq() {
  // @@protoc_insertion_point(destructor:ToDoService.v1.AddItemReq)
  SharedDtor(*this);
}
inline void AddItemReq::SharedDtor(MessageLite& self) {
  AddItemReq& this_ = static_cast<AddItemReq&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.description_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL AddItemReq::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) AddItemReq(arena);
}
constexpr auto AddItemReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(AddItemReq),
                                            alignof(AddItemReq));
}
constexpr auto AddItemReq::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_AddItemReq_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &AddItemReq::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<AddItemReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &AddItemReq::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<AddItemReq>(), &AddItemReq::ByteSizeLong,
              &AddItemReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(AddItemReq, _impl_._cached_size_),
          false,
      },
      &AddItemReq::kDescriptorMethods,
      &descriptor_table_todo_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull AddItemReq_class_data_ =
        AddItemReq::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
AddItemReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&AddItemReq_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(AddItemReq_class_data_.tc_table);
  return AddItemReq_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 45, 2>
AddItemReq::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AddItemReq, _impl_._has_bits_),
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967293,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    AddItemReq_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ToDoService::v1::AddItemReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string description = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(AddItemReq, _impl_.description_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string description = 2;
    {PROTOBUF_FIELD_OFFSET(AddItemReq, _impl_.description_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\13\0\0\0\0\0\0"
    "ToDoService.v1.AddItemReq"
    "description"
  }},
};
PROTOBUF_NOINLINE void AddItemReq::Clear() {
// @@protoc_insertion_point(message_clear_start:ToDoService.v1.AddItemReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.description_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL AddItemReq::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const AddItemReq& this_ = static_cast<const AddItemReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL AddItemReq::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const AddItemReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:ToDoService.v1.AddItemReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string description = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_description().empty()) {
      const ::std::string& _s = this_._internal_description();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ToDoService.v1.AddItemReq.description");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ToDoService.v1.AddItemReq)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t AddItemReq::ByteSizeLong(const MessageLite& base) {
  const AddItemReq& this_ = static_cast<const AddItemReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t AddItemReq::ByteSizeLong() const {
  const AddItemReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:ToDoService.v1.AddItemReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string description = 2;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_description().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_description());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void AddItemReq::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AddItemReq*>(&to_msg);
  auto& from = static_cast<const AddItemReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ToDoService.v1.AddItemReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_description().empty()) {
      _this->_internal_set_description(from._internal_description());
    } else {
      if (_this->_impl_.description_.IsDefault()) {
        _this->_internal_set_description("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AddItemReq::CopyFrom(const AddItemReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ToDoService.v1.AddItemReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AddItemReq::InternalSwap(AddItemReq* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.description_, &other->_impl_.description_, arena);
}

::google::protobuf::Metadata AddItemReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AddItemRes::_Internal {
 public:
};

AddItemRes::AddItemRes(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, AddItemRes_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:ToDoService.v1.AddItemRes)
}
AddItemRes::AddItemRes(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const AddItemRes& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, AddItemRes_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AddItemRes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:ToDoService.v1.AddItemRes)
}

inline void* PROTOBUF_NONNULL AddItemRes::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) AddItemRes(arena);
}
constexpr auto AddItemRes::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(AddItemRes),
                                            alignof(AddItemRes));
}
constexpr auto AddItemRes::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_AddItemRes_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &AddItemRes::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<AddItemRes>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &AddItemRes::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<AddItemRes>(), &AddItemRes::ByteSizeLong,
              &AddItemRes::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(AddItemRes, _impl_._cached_size_),
          false,
      },
      &AddItemRes::kDescriptorMethods,
      &descriptor_table_todo_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull AddItemRes_class_data_ =
        AddItemRes::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
AddItemRes::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&AddItemRes_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(AddItemRes_class_data_.tc_table);
  return AddItemRes_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
AddItemRes::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    AddItemRes_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ToDoService::v1::AddItemRes>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata AddItemRes::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UpdateItemReq::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<UpdateItemReq>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(UpdateItemReq, _impl_._has_bits_);
};

UpdateItemReq::UpdateItemReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, UpdateItemReq_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ToDoService.v1.UpdateItemReq)
}
PROTOBUF_NDEBUG_INLINE UpdateItemReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::ToDoService::v1::UpdateItemReq& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

UpdateItemReq::UpdateItemReq(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const UpdateItemReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, UpdateItemReq_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UpdateItemReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.todo_ = ((cached_has_bits & 0x00000001u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.todo_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:ToDoService.v1.UpdateItemReq)
}
PROTOBUF_NDEBUG_INLINE UpdateItemReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void UpdateItemReq::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.todo_ = {};
}
UpdateItemReq::~UpdateItemReq() {
  // @@protoc_insertion_point(destructor:ToDoService.v1.UpdateItemReq)
  SharedDtor(*this);
}
inline void UpdateItemReq::SharedDtor(MessageLite& self) {
  UpdateItemReq& this_ = static_cast<UpdateItemReq&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.todo_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL UpdateItemReq::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) UpdateItemReq(arena);
}
constexpr auto UpdateItemReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(UpdateItemReq),
                                            alignof(UpdateItemReq));
}
constexpr auto UpdateItemReq::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_UpdateItemReq_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &UpdateItemReq::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<UpdateItemReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &UpdateItemReq::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<UpdateItemReq>(), &UpdateItemReq::ByteSizeLong,
              &UpdateItemReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(UpdateItemReq, _impl_._cached_size_),
          false,
      },
      &UpdateItemReq::kDescriptorMethods,
      &descriptor_table_todo_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull UpdateItemReq_class_data_ =
        UpdateItemReq::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
UpdateItemReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&UpdateItemReq_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(UpdateItemReq_class_data_.tc_table);
  return UpdateItemReq_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
UpdateItemReq::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(UpdateItemReq, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    UpdateItemReq_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ToDoService::v1::UpdateItemReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .ToDoService.v1.ToDo todo = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(UpdateItemReq, _impl_.todo_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .ToDoService.v1.ToDo todo = 1;
    {PROTOBUF_FIELD_OFFSET(UpdateItemReq, _impl_.todo_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::ToDoService::v1::ToDo>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void UpdateItemReq::Clear() {
// @@protoc_insertion_point(message_clear_start:ToDoService.v1.UpdateItemReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    ABSL_DCHECK(_impl_.todo_ != nullptr);
    _impl_.todo_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL UpdateItemReq::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const UpdateItemReq& this_ = static_cast<const UpdateItemReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL UpdateItemReq::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const UpdateItemReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:ToDoService.v1.UpdateItemReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .ToDoService.v1.ToDo todo = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.todo_, this_._impl_.todo_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ToDoService.v1.UpdateItemReq)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t UpdateItemReq::ByteSizeLong(const MessageLite& base) {
  const UpdateItemReq& this_ = static_cast<const UpdateItemReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t UpdateItemReq::ByteSizeLong() const {
  const UpdateItemReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:ToDoService.v1.UpdateItemReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // .ToDoService.v1.ToDo todo = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.todo_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void UpdateItemReq::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UpdateItemReq*>(&to_msg);
  auto& from = static_cast<const UpdateItemReq&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:ToDoService.v1.UpdateItemReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    ABSL_DCHECK(from._impl_.todo_ != nullptr);
    if (_this->_impl_.todo_ == nullptr) {
      _this->_impl_.todo_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.todo_);
    } else {
      _this->_impl_.todo_->MergeFrom(*from._impl_.todo_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateItemReq::CopyFrom(const UpdateItemReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ToDoService.v1.UpdateItemReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UpdateItemReq::InternalSwap(UpdateItemReq* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.todo_, other->_impl_.todo_);
}

::google::protobuf::Metadata UpdateItemReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UpdateItemRes::_Internal {
 public:
};

UpdateItemRes::UpdateItemRes(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, UpdateItemRes_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:ToDoService.v1.UpdateItemRes)
}
UpdateItemRes::UpdateItemRes(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const UpdateItemRes& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, UpdateItemRes_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UpdateItemRes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:ToDoService.v1.UpdateItemRes)
}

inline void* PROTOBUF_NONNULL UpdateItemRes::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) UpdateItemRes(arena);
}
constexpr auto UpdateItemRes::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(UpdateItemRes),
                                            alignof(UpdateItemRes));
}
constexpr auto UpdateItemRes::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_UpdateItemRes_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &UpdateItemRes::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<UpdateItemRes>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &UpdateItemRes::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<UpdateItemRes>(), &UpdateItemRes::ByteSizeLong,
              &UpdateItemRes::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(UpdateItemRes, _impl_._cached_size_),
          false,
      },
      &UpdateItemRes::kDescriptorMethods,
      &descriptor_table_todo_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull UpdateItemRes_class_data_ =
        UpdateItemRes::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
UpdateItemRes::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&UpdateItemRes_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(UpdateItemRes_class_data_.tc_table);
  return UpdateItemRes_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
UpdateItemRes::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    UpdateItemRes_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ToDoService::v1::UpdateItemRes>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata UpdateItemRes::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class StreamUpdateChangeReq::_Internal {
 public:
};

StreamUpdateChangeReq::StreamUpdateChangeReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, StreamUpdateChangeReq_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:ToDoService.v1.StreamUpdateChangeReq)
}
StreamUpdateChangeReq::StreamUpdateChangeReq(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const StreamUpdateChangeReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, StreamUpdateChangeReq_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  StreamUpdateChangeReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:ToDoService.v1.StreamUpdateChangeReq)
}

inline void* PROTOBUF_NONNULL StreamUpdateChangeReq::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) StreamUpdateChangeReq(arena);
}
constexpr auto StreamUpdateChangeReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(StreamUpdateChangeReq),
                                            alignof(StreamUpdateChangeReq));
}
constexpr auto StreamUpdateChangeReq::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_StreamUpdateChangeReq_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &StreamUpdateChangeReq::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<StreamUpdateChangeReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &StreamUpdateChangeReq::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<StreamUpdateChangeReq>(), &StreamUpdateChangeReq::ByteSizeLong,
              &StreamUpdateChangeReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(StreamUpdateChangeReq, _impl_._cached_size_),
          false,
      },
      &StreamUpdateChangeReq::kDescriptorMethods,
      &descriptor_table_todo_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull StreamUpdateChangeReq_class_data_ =
        StreamUpdateChangeReq::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
StreamUpdateChangeReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&StreamUpdateChangeReq_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(StreamUpdateChangeReq_class_data_.tc_table);
  return StreamUpdateChangeReq_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
StreamUpdateChangeReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    StreamUpdateChangeReq_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ToDoService::v1::StreamUpdateChangeReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata StreamUpdateChangeReq::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class StreamUpdateChangeRes::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<StreamUpdateChangeRes>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(StreamUpdateChangeRes, _impl_._has_bits_);
};

StreamUpdateChangeRes::StreamUpdateChangeRes(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, StreamUpdateChangeRes_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ToDoService.v1.StreamUpdateChangeRes)
}
PROTOBUF_NDEBUG_INLINE StreamUpdateChangeRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::ToDoService::v1::StreamUpdateChangeRes& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

StreamUpdateChangeRes::StreamUpdateChangeRes(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const StreamUpdateChangeRes& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, StreamUpdateChangeRes_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  StreamUpdateChangeRes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.todo_ = ((cached_has_bits & 0x00000001u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.todo_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:ToDoService.v1.StreamUpdateChangeRes)
}
PROTOBUF_NDEBUG_INLINE StreamUpdateChangeRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void StreamUpdateChangeRes::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.todo_ = {};
}
StreamUpdateChangeRes::~StreamUpdateChangeRes() {
  // @@protoc_insertion_point(destructor:ToDoService.v1.StreamUpdateChangeRes)
  SharedDtor(*this);
}
inline void StreamUpdateChangeRes::SharedDtor(MessageLite& self) {
  StreamUpdateChangeRes& this_ = static_cast<StreamUpdateChangeRes&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.todo_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL StreamUpdateChangeRes::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) StreamUpdateChangeRes(arena);
}
constexpr auto StreamUpdateChangeRes::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(StreamUpdateChangeRes),
                                            alignof(StreamUpdateChangeRes));
}
constexpr auto StreamUpdateChangeRes::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_StreamUpdateChangeRes_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &StreamUpdateChangeRes::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<StreamUpdateChangeRes>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &StreamUpdateChangeRes::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<StreamUpdateChangeRes>(), &StreamUpdateChangeRes::ByteSizeLong,
              &StreamUpdateChangeRes::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(StreamUpdateChangeRes, _impl_._cached_size_),
          false,
      },
      &StreamUpdateChangeRes::kDescriptorMethods,
      &descriptor_table_todo_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull StreamUpdateChangeRes_class_data_ =
        StreamUpdateChangeRes::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
StreamUpdateChangeRes::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&StreamUpdateChangeRes_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(StreamUpdateChangeRes_class_data_.tc_table);
  return StreamUpdateChangeRes_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
StreamUpdateChangeRes::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(StreamUpdateChangeRes, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    StreamUpdateChangeRes_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ToDoService::v1::StreamUpdateChangeRes>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .ToDoService.v1.ToDo todo = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(StreamUpdateChangeRes, _impl_.todo_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .ToDoService.v1.ToDo todo = 1;
    {PROTOBUF_FIELD_OFFSET(StreamUpdateChangeRes, _impl_.todo_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::ToDoService::v1::ToDo>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void StreamUpdateChangeRes::Clear() {
// @@protoc_insertion_point(message_clear_start:ToDoService.v1.StreamUpdateChangeRes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    ABSL_DCHECK(_impl_.todo_ != nullptr);
    _impl_.todo_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL StreamUpdateChangeRes::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const StreamUpdateChangeRes& this_ = static_cast<const StreamUpdateChangeRes&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL StreamUpdateChangeRes::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const StreamUpdateChangeRes& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:ToDoService.v1.StreamUpdateChangeRes)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .ToDoService.v1.ToDo todo = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.todo_, this_._impl_.todo_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ToDoService.v1.StreamUpdateChangeRes)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t StreamUpdateChangeRes::ByteSizeLong(const MessageLite& base) {
  const StreamUpdateChangeRes& this_ = static_cast<const StreamUpdateChangeRes&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t StreamUpdateChangeRes::ByteSizeLong() const {
  const StreamUpdateChangeRes& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:ToDoService.v1.StreamUpdateChangeRes)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // .ToDoService.v1.ToDo todo = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.todo_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void StreamUpdateChangeRes::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<StreamUpdateChangeRes*>(&to_msg);
  auto& from = static_cast<const StreamUpdateChangeRes&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:ToDoService.v1.StreamUpdateChangeRes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    ABSL_DCHECK(from._impl_.todo_ != nullptr);
    if (_this->_impl_.todo_ == nullptr) {
      _this->_impl_.todo_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.todo_);
    } else {
      _this->_impl_.todo_->MergeFrom(*from._impl_.todo_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void StreamUpdateChangeRes::CopyFrom(const StreamUpdateChangeRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ToDoService.v1.StreamUpdateChangeRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void StreamUpdateChangeRes::InternalSwap(StreamUpdateChangeRes* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.todo_, other->_impl_.todo_);
}

::google::protobuf::Metadata StreamUpdateChangeRes::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace ToDoService
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_todo_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
